export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: "img/pattern.jpg",
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build your brand",
    img: "img/maintitle.png",
  },
  {
    id: 3,
    title: "Wordpress",
    desc: "Customize your site",
    img: "img/pattern.jpg",
  },
  {
    id: 4,
    title: "Voice Over",
    desc: "Share your message",
    img: "img/pattern.jpg",
  },
  {
    id: 5,
    title: "Video Explainer",
    desc: "Engage your audience",
    img: "img/pattern.jpg",
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Reach more customers",
    img: "img/pattern.jpg",
  },
  {
    id: 7,
    title: "SEO",
    desc: "Unlock growth online",
    img: "img/pattern.jpg",
  },
  {
    id: 8,
    title: "Illustration",
    desc: "Color your dreams",
    img: "img/pattern.jpg",
  },
  {
    id: 9,
    title: "Translation",
    desc: "Go global",
    img: "img/pattern.jpg",
  },
  {
    id: 10,
    title: "Data Entry",
    desc: "Learn your business",
    img: "img/pattern.jpg",
  },
  {
    id: 11,
    title: "Book Covers",
    desc: "Showcase your story",
    img: "img/pattern.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "img/pattern.jpg",
    pp: "img/pattern.jpg",
    cat: "Category1",
    username: "Angel Eye",
  },
  {
    id: 2,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category2",
    username: "Anna Pearl",
  },
  {
    id: 3,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category3",
    username: "Anna Pearl",
  },
  {
    id: 4,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category4",
    username: "Anna Pearl",
  },
  {
    id: 5,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category5",
    username: "Anna Pearl",
  },
  {
    id: 6,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category6",
    username: "Anna Pearl",
  },
  {
    id: 7,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category7",
    username: "Anna Pearl",
  },
  {
    id: 8,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category8",
    username: "Anna Pearl",
  },
  {
    id: 9,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category9",
    username: "Anna Pearl",
  },
  {
    id: 10,
    img: "img/pattern.jpg",
    pp: "img/bg.jpg",
    cat: "Category10",
    username: "Anna Pearl",
  },
];
